# Generated by Django 2.1.15 on 2020-05-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eployee_app', '0002_auto_20200516_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Mobile_no',
            field=models.CharField(max_length=11),
        ),
    ]
